# invest
qiufei  



# younger



```
##     As of 0.4-0, 'getSymbols' uses env=parent.frame() and
##  auto.assign=TRUE by default.
## 
##  This  behavior  will be  phased out in 0.5-0  when the call  will
##  default to use auto.assign=FALSE. getOption("getSymbols.env") and 
##  getOptions("getSymbols.auto.assign") are now checked for alternate defaults
## 
##  This message is shown once per session and may be disabled by setting 
##  options("getSymbols.warning4.0"=FALSE). See ?getSymbols for more details.
```

```
## [1] "YOUNGER"
```

```
##      Index            600177.SS.Close
##  Min.   :1998-11-19   Min.   : 3.11  
##  1st Qu.:2003-02-04   1st Qu.: 7.68  
##  Median :2007-04-20   Median :10.58  
##  Mean   :2007-04-28   Mean   :11.79  
##  3rd Qu.:2011-07-25   3rd Qu.:14.04  
##  Max.   :2015-10-20   Max.   :33.48
```

```
##      Index            600177.SS.Close
##  Min.   :2008-06-02   Min.   : 5.65  
##  1st Qu.:2009-12-14   1st Qu.: 7.86  
##  Median :2011-07-14   Median : 9.96  
##  Mean   :2011-07-25   Mean   :10.15  
##  3rd Qu.:2013-02-01   3rd Qu.:11.78  
##  Max.   :2015-10-20   Max.   :18.17
```

```
##      Index            600177.SS.Close
##  Min.   :2015-08-03   Min.   :11.45  
##  1st Qu.:2015-08-21   1st Qu.:12.62  
##  Median :2015-09-10   Median :13.06  
##  Mean   :2015-09-10   Mean   :13.92  
##  3rd Qu.:2015-09-30   3rd Qu.:14.19  
##  Max.   :2015-10-20   Max.   :18.17
```
the longtime median of younger is 10.58,10.58; the normal time median of younger is 10.10343,9.96;the recent time median of younger is 13.285,13.06.

that is to say that you can purchase younger between 10.58~13.06 relatively safe.


# sh


```
## [1] "SHDEX"
```

```
##      Index            000001.SS.Close
##  Min.   :2008-06-02   Min.   :1707   
##  1st Qu.:2009-11-26   1st Qu.:2156   
##  Median :2011-05-26   Median :2419   
##  Mean   :2011-06-24   Mean   :2509   
##  3rd Qu.:2012-12-20   3rd Qu.:2849   
##  Max.   :2015-10-16   Max.   :3965
```

```
##      Index            000001.SS.Close
##  Min.   :2015-08-03   Min.   :2927   
##  1st Qu.:2015-08-18   1st Qu.:3115   
##  Median :2015-09-01   Median :3210   
##  Mean   :2015-09-03   Mean   :3363   
##  3rd Qu.:2015-09-17   3rd Qu.:3664   
##  Max.   :2015-10-16   Max.   :3965
```
the shdex mormal time median is 2419,2418.775.

the shdex rencent time median is 3210, the 1st quantile is 3115, the minimum is 2927.

**next step find the stock whose (last day price - median)/median is the smallest**


# plot using quantmod




# convert xts into dataframe


